/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collection/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection Capabilities */
        get: operations["collection_capabilities_api_v1_collection_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emergency-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Global */
        post: operations["activate_global_api_v1_emergency_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emergency-controls/{control_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Global */
        post: operations["deactivate_global_api_v1_emergency_controls__control_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_organizations__organization_id__audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Authorizations */
        get: operations["list_authorizations_api_v1_organizations__organization_id__authorizations_get"];
        put?: never;
        /** Create Authorization */
        post: operations["create_authorization_api_v1_organizations__organization_id__authorizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations/{authorization_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Authorization */
        post: operations["accept_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations/{authorization_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Authorization */
        post: operations["revoke_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Domains */
        get: operations["list_domains_api_v1_organizations__organization_id__domains_get"];
        put?: never;
        /** Create Domain */
        post: operations["create_domain_api_v1_organizations__organization_id__domains_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain */
        get: operations["get_domain_api_v1_organizations__organization_id__domains__domain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Challenge */
        post: operations["create_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Challenge */
        delete: operations["revoke_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges/{challenge_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Challenge */
        post: operations["verify_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/emergency-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Controls */
        get: operations["list_controls_api_v1_organizations__organization_id__emergency_controls_get"];
        put?: never;
        /** Activate */
        post: operations["activate_api_v1_organizations__organization_id__emergency_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/emergency-controls/{control_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate */
        post: operations["deactivate_api_v1_organizations__organization_id__emergency_controls__control_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_api_v1_organizations__organization_id__evidence_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["list_findings_api_v1_organizations__organization_id__evidence_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/findings/{finding_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Finding Event */
        post: operations["create_finding_event_api_v1_organizations__organization_id__evidence_findings__finding_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/findings/{finding_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finding History */
        get: operations["finding_history_api_v1_organizations__organization_id__evidence_findings__finding_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/fixture-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture Export */
        get: operations["fixture_export_api_v1_organizations__organization_id__evidence_fixture_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/evidence/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_v1_organizations__organization_id__evidence_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_api_v1_organizations__organization_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memberships */
        get: operations["list_memberships_api_v1_organizations__organization_id__memberships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/memberships/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Membership */
        delete: operations["revoke_membership_api_v1_organizations__organization_id__memberships__membership_id__delete"];
        options?: never;
        head?: never;
        /** Change Membership */
        patch: operations["change_membership_api_v1_organizations__organization_id__memberships__membership_id__patch"];
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentAuthorizationCreate */
        AssessmentAuthorizationCreate: {
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Domain Ids */
            domain_ids: string[];
            /** Operation Classes */
            operation_classes: ("dns_verification" | "https_verification" | "passive_assessment" | "active_assessment")[];
            /** Policy Version */
            policy_version: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** AssessmentAuthorizationResponse */
        AssessmentAuthorizationResponse: {
            /** Consent Version */
            consent_version: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operation Classes */
            operation_classes: string[];
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Policy Version */
            policy_version: string;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "active" | "expired" | "revoked";
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor */
            actor: {
                [key: string]: string;
            };
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Correlation Id */
            correlation_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Organization Id */
            organization_id: string | null;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id: string;
            /** Resource */
            resource: {
                [key: string]: string;
            };
        };
        /** AuthorizationRevoke */
        AuthorizationRevoke: {
            /** Reason */
            reason: string;
        };
        /** CheckEvaluationResponse */
        CheckEvaluationResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Check Id */
            check_id: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /**
             * Evidence Mode
             * @enum {string}
             */
            evidence_mode: "fixture" | "live";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Methodology Version */
            methodology_version: string;
            /** Outcome */
            outcome: string;
            /** Publishable */
            publishable: boolean;
            /** Reason Code */
            reason_code: string;
            /** Scoring Behavior Version */
            scoring_behavior_version: string;
        };
        /** CollectionCapabilityResponse */
        CollectionCapabilityResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            execution_modes?: components["schemas"]["CollectionExecutionModes"];
            /**
             * Fixture Only
             * @default true
             * @constant
             */
            fixture_only: true;
            /**
             * Live Execution
             * @default false
             * @constant
             */
            live_execution: false;
            /**
             * Milestone Status
             * @default fixture_validation_only
             * @constant
             */
            milestone_status: "fixture_validation_only";
            /**
             * Publishable
             * @default false
             * @constant
             */
            publishable: false;
            /**
             * Report Banner
             * @default FIXTURE DATA — NOT A LIVE ASSESSMENT
             * @constant
             */
            report_banner: "FIXTURE DATA — NOT A LIVE ASSESSMENT";
            /**
             * Restricted Egress Boundary
             * @default required_before_live_activation
             * @constant
             */
            restricted_egress_boundary: "required_before_live_activation";
        };
        /** CollectionExecutionModes */
        CollectionExecutionModes: {
            /**
             * Disabled By Policy
             * @default structured_result_state
             * @constant
             */
            disabled_by_policy: "structured_result_state";
            /**
             * Fixture
             * @default available
             * @constant
             */
            fixture: "available";
            /**
             * Live
             * @default future_requires_explicit_activation
             * @constant
             */
            live: "future_requires_explicit_activation";
            /**
             * Unavailable
             * @default structured_result_state
             * @constant
             */
            unavailable: "structured_result_state";
        };
        /** DomainChallengeCreate */
        DomainChallengeCreate: {
            /**
             * Method
             * @enum {string}
             */
            method: "dns_txt" | "https_file";
        };
        /** DomainChallengeCreatedResponse */
        DomainChallengeCreatedResponse: {
            /** Attempts Remaining */
            attempts_remaining: number;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "dns_txt" | "https_file";
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "verified" | "expired" | "failed" | "revoked";
            /** Verification Location */
            verification_location: string;
            /** Verification Token */
            verification_token: string;
        };
        /** DomainCreate */
        DomainCreate: {
            /** Domain */
            domain: string;
        };
        /** DomainResponse */
        DomainResponse: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Ownership State
             * @enum {string}
             */
            ownership_state: "pending" | "verified" | "expired" | "failed" | "revoked" | "reverification_required";
            /** Registrable Domain */
            registrable_domain: string;
            /** Unicode Display */
            unicode_display: string;
            /** Warnings */
            warnings: ("idn_present" | "mixed_scripts")[];
        };
        /** EmergencyControlCreate */
        EmergencyControlCreate: {
            /** Domain Id */
            domain_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Operation Class */
            operation_class?: ("dns_verification" | "https_verification" | "passive_assessment" | "active_assessment") | null;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "global" | "organization" | "domain" | "operation_class";
        };
        /** EmergencyControlDeactivate */
        EmergencyControlDeactivate: {
            /** Reason */
            reason: string;
        };
        /** EmergencyControlResponse */
        EmergencyControlResponse: {
            /** Active */
            active: boolean;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain Id */
            domain_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operation Class */
            operation_class?: string | null;
            /** Organization Id */
            organization_id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "global" | "organization" | "domain" | "operation_class";
        };
        /** EvidenceExportResponse */
        EvidenceExportResponse: {
            /**
             * Classification
             * @constant
             */
            classification: "DEMO/FIXTURE";
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Disclaimer
             * @constant
             */
            disclaimer: "Fixture-only demonstration; not a live internet assessment.";
            /**
             * Evidence Mode
             * @constant
             */
            evidence_mode: "fixture";
            /** Finding Count */
            finding_count: number;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Publishable
             * @constant
             */
            publishable: false;
            /** Snapshot Count */
            snapshot_count: number;
        };
        /** FindingEventCreate */
        FindingEventCreate: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "suppressed" | "accepted_risk" | "reopened" | "remediation_verified";
            /** Reason */
            reason: string;
            /** Review At */
            review_at?: string | null;
        };
        /** FindingEventResponse */
        FindingEventResponse: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string;
            /** Request Id */
            request_id: string;
            /** Review At */
            review_at: string | null;
            /** Scope Reference */
            scope_reference: string;
        };
        /** FindingResponse */
        FindingResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Check Id */
            check_id: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "DEMO/FIXTURE" | "PRIVATE";
            /**
             * Evidence Mode
             * @enum {string}
             */
            evidence_mode: "fixture" | "live";
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Publishable */
            publishable: boolean;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high" | "critical";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** InvitationAccept */
        InvitationAccept: {
            /** Token */
            token: string;
        };
        /** InvitationCreate */
        InvitationCreate: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "organization_owner" | "security_admin" | "analyst" | "viewer_auditor" | "maturity_contributor";
        };
        /** InvitationCreatedResponse */
        InvitationCreatedResponse: {
            /** Acceptance Token */
            acceptance_token: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** InvitationResponse */
        InvitationResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Logout Url */
            logout_url: string | null;
        };
        /** MembershipResponse */
        MembershipResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipUpdate */
        MembershipUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "organization_owner" | "security_admin" | "analyst" | "viewer_auditor" | "maturity_contributor";
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ScopeManifestResponse */
        ScopeManifestResponse: {
            /**
             * Algorithm
             * @default EdDSA
             * @constant
             */
            algorithm: "EdDSA";
            /**
             * Authorization Id
             * Format: uuid
             */
            authorization_id: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Id */
            key_id: string;
            /**
             * Manifest Version
             * @default v1
             * @constant
             */
            manifest_version: "v1";
            /** Payload Sha256 */
            payload_sha256: string;
        };
        /** ScoreSnapshotResponse */
        ScoreSnapshotResponse: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Attribution Confidence */
            attribution_confidence: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "DEMO/FIXTURE" | "PRIVATE";
            /** Coverage */
            coverage: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Confidence */
            evidence_confidence: number;
            /**
             * Evidence Mode
             * @enum {string}
             */
            evidence_mode: "fixture" | "live";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Methodology Version */
            methodology_version: string;
            /** Publishable */
            publishable: boolean;
            /** Technical Posture */
            technical_posture: number | null;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Authenticated
             * @default true
             * @constant
             */
            authenticated: true;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Csrf Token */
            csrf_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_api_v1_auth_callback_get: {
        parameters: {
            query: {
                state: string;
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_get: {
        parameters: {
            query?: {
                return_path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collection_capabilities_api_v1_collection_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionCapabilityResponse"];
                };
            };
        };
    };
    activate_global_api_v1_emergency_controls_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_global_api_v1_emergency_controls__control_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                control_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlDeactivate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_organizations__organization_id__audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_authorizations_api_v1_organizations__organization_id__authorizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_authorization_api_v1_organizations__organization_id__authorizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentAuthorizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                authorization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeManifestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                authorization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizationRevoke"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_domains_api_v1_organizations__organization_id__domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_domain_api_v1_organizations__organization_id__domains_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_api_v1_organizations__organization_id__domains__domain_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainChallengeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainChallengeCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
                challenge_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
                challenge_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_controls_api_v1_organizations__organization_id__emergency_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_v1_organizations__organization_id__emergency_controls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_v1_organizations__organization_id__emergency_controls__control_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                control_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlDeactivate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_api_v1_organizations__organization_id__evidence_evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckEvaluationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_organizations__organization_id__evidence_findings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_finding_event_api_v1_organizations__organization_id__evidence_findings__finding_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                finding_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_history_api_v1_organizations__organization_id__evidence_findings__finding_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                finding_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_export_api_v1_organizations__organization_id__evidence_fixture_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_organizations__organization_id__evidence_snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreSnapshotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_organizations__organization_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memberships_api_v1_organizations__organization_id__memberships_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_membership_api_v1_organizations__organization_id__memberships__membership_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                membership_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_membership_api_v1_organizations__organization_id__memberships__membership_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                membership_id: string;
            };
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-siembiot_session"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
