/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/emergency-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Global */
        post: operations["activate_global_api_v1_emergency_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emergency-controls/{control_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Global */
        post: operations["deactivate_global_api_v1_emergency_controls__control_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Touches nothing, so a dependency outage cannot restart the fleet.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_api_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations_api_v1_organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_api_v1_organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization_api_v1_organizations__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_v1_organizations__organization_id__assessments_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_organizations__organization_id__assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show */
        get: operations["show_api_v1_organizations__organization_id__assessments__assessment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/assessments/{assessment_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description Request cancellation. Work in flight observes it and settles itself.
         */
        post: operations["cancel_api_v1_organizations__organization_id__assessments__assessment_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/asset-candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Accept or reject a candidate.
         *
         *     Accepting decides what may be assessed, so it is attributable and audited.
         */
        post: operations["decide_api_v1_organizations__organization_id__asset_candidates__candidate_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_api_v1_organizations__organization_id__audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Authorizations */
        get: operations["list_authorizations_api_v1_organizations__organization_id__authorizations_get"];
        put?: never;
        /** Create Authorization */
        post: operations["create_authorization_api_v1_organizations__organization_id__authorizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations/{authorization_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Authorization */
        post: operations["accept_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/authorizations/{authorization_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Authorization */
        post: operations["revoke_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Domains */
        get: operations["list_domains_api_v1_organizations__organization_id__domains_get"];
        put?: never;
        /** Create Domain */
        post: operations["create_domain_api_v1_organizations__organization_id__domains_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain */
        get: operations["get_domain_api_v1_organizations__organization_id__domains__domain_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/asset-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_v1_organizations__organization_id__domains__domain_id__asset_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Challenge */
        post: operations["create_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Challenge */
        delete: operations["revoke_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/challenges/{challenge_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Challenge */
        post: operations["verify_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_v1_organizations__organization_id__domains__domain_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_v1_organizations__organization_id__domains__domain_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/domains/{domain_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_organizations__organization_id__domains__domain_id__schedule_get"];
        /** Update */
        put: operations["update_api_v1_organizations__organization_id__domains__domain_id__schedule_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/emergency-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Controls */
        get: operations["list_controls_api_v1_organizations__organization_id__emergency_controls_get"];
        put?: never;
        /** Activate */
        post: operations["activate_api_v1_organizations__organization_id__emergency_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/emergency-controls/{control_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate */
        post: operations["deactivate_api_v1_organizations__organization_id__emergency_controls__control_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_api_v1_organizations__organization_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memberships */
        get: operations["list_memberships_api_v1_organizations__organization_id__memberships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organization_id}/memberships/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Membership */
        delete: operations["revoke_membership_api_v1_organizations__organization_id__memberships__membership_id__delete"];
        options?: never;
        head?: never;
        /** Change Membership */
        patch: operations["change_membership_api_v1_organizations__organization_id__memberships__membership_id__patch"];
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness. Answers whether this replica can serve a request right now.
         *
         *     Returns 503 when it cannot, because an orchestrator reads the status code, and
         *     a body saying `ready: false` behind a 200 would keep traffic arriving.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session
         * @description Report who the upstream authentication layer says the caller is.
         */
        get: operations["session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssessmentAuthorizationCreate */
        AssessmentAuthorizationCreate: {
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Domain Ids */
            domain_ids: string[];
            /** Operation Classes */
            operation_classes: ("dns_verification" | "https_verification" | "passive_assessment" | "active_assessment")[];
            /** Policy Version */
            policy_version: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** AssessmentAuthorizationResponse */
        AssessmentAuthorizationResponse: {
            /** Consent Version */
            consent_version: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operation Classes */
            operation_classes: string[];
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Policy Version */
            policy_version: string;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "active" | "expired" | "revoked";
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
        };
        /** AssessmentCancel */
        AssessmentCancel: {
            /** Reason */
            reason: string;
        };
        /**
         * AssessmentChangeResponse
         * @description What moved between two runs, and whether the comparison means anything.
         *
         *     `comparable` is the honest part. A score that rose because coverage fell is not an
         *     improvement -- it is a different question, answered against less evidence. When the
         *     two runs did not see the same amount, the deltas are still reported but the flag
         *     says not to read them as progress.
         */
        AssessmentChangeResponse: {
            /** Comparable */
            comparable: boolean;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Coverage Delta */
            coverage_delta: number;
            /**
             * Current Assessment Id
             * Format: uuid
             */
            current_assessment_id: string;
            /** Incomparable Reason */
            incomparable_reason?: string | null;
            /** Opened */
            opened?: components["schemas"]["FindingChangeResponse"][];
            /**
             * Previous Assessment Id
             * Format: uuid
             */
            previous_assessment_id: string;
            /** Resolved */
            resolved?: components["schemas"]["FindingChangeResponse"][];
            /** Score Delta */
            score_delta: number;
            /**
             * Unchanged Count
             * @default 0
             */
            unchanged_count: number;
        };
        /** AssessmentCreate */
        AssessmentCreate: {
            /** Dkim Selectors */
            dkim_selectors?: string[];
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Mode
             * @default passive_observation
             * @enum {string}
             */
            mode: "passive_observation" | "authorized_assessment";
        };
        /**
         * AssessmentProgressResponse
         * @description Progress counted from settled steps, never from elapsed time.
         */
        AssessmentProgressResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Failed Steps */
            failed_steps: string[];
            /** Percentage */
            percentage: number;
            /** Settled Steps */
            settled_steps: number;
            /** Succeeded Steps */
            succeeded_steps: number;
            /** Total Steps */
            total_steps: number;
        };
        /** AssessmentResponse */
        AssessmentResponse: {
            /** Band */
            band?: string | null;
            /**
             * Cancellation Requested
             * @default false
             */
            cancellation_requested: boolean;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Coverage Percentage */
            coverage_percentage?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Methodology Version */
            methodology_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "passive_observation" | "authorized_assessment";
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            progress: components["schemas"]["AssessmentProgressResponse"];
            /** Score */
            score?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "draft" | "awaiting_authorization" | "queued" | "planning" | "collecting" | "normalizing" | "evaluating" | "agent_analysis" | "report_generation" | "completed" | "cancelled" | "partially_completed" | "failed" | "expired" | "blocked_by_policy";
            /** Steps */
            steps?: components["schemas"]["AssessmentStepResponse"][];
        };
        /** AssessmentStepResponse */
        AssessmentStepResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Last Error */
            last_error?: string | null;
            /** Name */
            name: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "succeeded" | "failed" | "skipped" | "cancelled" | "dead_lettered";
        };
        /** AssetCandidateDecision */
        AssetCandidateDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accepted" | "rejected";
            /** Reason */
            reason?: string | null;
        };
        /** AssetCandidateResponse */
        AssetCandidateResponse: {
            /**
             * Attribution Basis
             * @enum {string}
             */
            attribution_basis: "authorized_domain" | "subdomain_of_authorized_domain" | "unrelated_name";
            /** Attribution Confidence */
            attribution_confidence: number;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Name */
            name: string;
            /** Observation Count */
            observation_count: number;
            /** Shared Hosting */
            shared_hosting: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "certificate_transparency" | "dns" | "user_declared" | "passive_intelligence";
            /**
             * State
             * @enum {string}
             */
            state: "unreviewed" | "accepted" | "rejected";
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor */
            actor: {
                [key: string]: string;
            };
            /** Context */
            context: {
                [key: string]: unknown;
            };
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Correlation Id */
            correlation_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Organization Id */
            organization_id: string | null;
            /** Outcome */
            outcome: string;
            /** Request Id */
            request_id: string;
            /** Resource */
            resource: {
                [key: string]: string;
            };
        };
        /** AuthorizationRevoke */
        AuthorizationRevoke: {
            /** Reason */
            reason: string;
        };
        /** DomainChallengeCreate */
        DomainChallengeCreate: {
            /**
             * Method
             * @enum {string}
             */
            method: "dns_txt" | "https_file";
        };
        /** DomainChallengeCreatedResponse */
        DomainChallengeCreatedResponse: {
            /** Attempts Remaining */
            attempts_remaining: number;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Method
             * @enum {string}
             */
            method: "dns_txt" | "https_file";
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "verified" | "expired" | "failed" | "revoked";
            /** Verification Location */
            verification_location: string;
            /** Verification Token */
            verification_token: string;
        };
        /** DomainCreate */
        DomainCreate: {
            /** Domain */
            domain: string;
        };
        /** DomainFindingsResponse */
        DomainFindingsResponse: {
            /** Assessment Id */
            assessment_id?: string | null;
            /** Band */
            band?: string | null;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Coverage Percentage */
            coverage_percentage?: number | null;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /** Findings */
            findings?: components["schemas"]["FindingResponse"][];
            /** Methodology Version */
            methodology_version?: string | null;
            /** Score */
            score?: number | null;
            summary: components["schemas"]["FindingSummaryResponse"];
        };
        /** DomainHistoryResponse */
        DomainHistoryResponse: {
            change?: components["schemas"]["AssessmentChangeResponse"] | null;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /** Points */
            points?: components["schemas"]["HistoryPointResponse"][];
        };
        /** DomainResponse */
        DomainResponse: {
            /** Canonical Name */
            canonical_name: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Ownership State
             * @enum {string}
             */
            ownership_state: "pending" | "verified" | "expired" | "failed" | "revoked" | "reverification_required";
            /** Registrable Domain */
            registrable_domain: string;
            /** Unicode Display */
            unicode_display: string;
            /** Warnings */
            warnings: ("idn_present" | "mixed_scripts")[];
        };
        /** EmergencyControlCreate */
        EmergencyControlCreate: {
            /** Domain Id */
            domain_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Operation Class */
            operation_class?: ("dns_verification" | "https_verification" | "passive_assessment" | "active_assessment") | null;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "global" | "organization" | "domain" | "operation_class";
        };
        /** EmergencyControlDeactivate */
        EmergencyControlDeactivate: {
            /** Reason */
            reason: string;
        };
        /** EmergencyControlResponse */
        EmergencyControlResponse: {
            /** Active */
            active: boolean;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Domain Id */
            domain_id?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Operation Class */
            operation_class?: string | null;
            /** Organization Id */
            organization_id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "global" | "organization" | "domain" | "operation_class";
        };
        /** FindingChangeResponse */
        FindingChangeResponse: {
            /** Check Id */
            check_id: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "informational";
            /** Title En */
            title_en: string;
            /** Title Ro */
            title_ro: string;
        };
        /**
         * FindingConfidenceResponse
         * @description Three separate confidences, never averaged into one reassuring number.
         *
         *     Attribution, source and freshness fail independently and mean different things: a
         *     finding can rest on excellent evidence about an asset that may not be yours. A
         *     single blended figure would hide exactly the distinction a reader needs.
         */
        FindingConfidenceResponse: {
            /** Attribution */
            attribution: number;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Freshness */
            freshness: number;
            /** Source */
            source: number;
        };
        /** FindingResponse */
        FindingResponse: {
            /** Check Id */
            check_id: string;
            /** Check Version */
            check_version: string;
            confidence: components["schemas"]["FindingConfidenceResponse"];
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Methodology Version */
            methodology_version: string;
            /** Pillar */
            pillar: string;
            /** Pillar Letter */
            pillar_letter: string;
            /** Rationale En */
            rationale_en: string;
            /** Rationale Ro */
            rationale_ro: string;
            /** Reason Code */
            reason_code?: string | null;
            /** References */
            references?: string[];
            remediation?: components["schemas"]["RemediationResponse"] | null;
            /** Remediation Template */
            remediation_template?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low" | "informational";
            /**
             * State
             * @enum {string}
             */
            state: "open" | "resolved" | "regressed" | "suppressed" | "accepted_risk";
            /** Subject Identifier */
            subject_identifier: string;
            /** Subject Kind */
            subject_kind: string;
            /** Title En */
            title_en: string;
            /** Title Ro */
            title_ro: string;
        };
        /**
         * FindingSummaryResponse
         * @description Counts by severity, so a reader sees the shape before the list.
         */
        FindingSummaryResponse: {
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Open */
            open: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness: this process is running and not wedged.
         *
         *     Deliberately answers without touching the database. A liveness probe that fails
         *     during a database outage makes an orchestrator restart every replica, which does
         *     not fix the database and does delay recovery once it returns.
         */
        HealthResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * HistoryPointResponse
         * @description One completed assessment, as a point on a timeline.
         */
        HistoryPointResponse: {
            /**
             * Assessment Id
             * Format: uuid
             */
            assessment_id: string;
            /** Band */
            band: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Coverage Percentage */
            coverage_percentage: number;
            /** Coverage Sufficient */
            coverage_sufficient: boolean;
            /** Methodology Version */
            methodology_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "passive_observation" | "authorized_assessment";
            /** Score */
            score: number;
        };
        /** InvitationAccept */
        InvitationAccept: {
            /** Token */
            token: string;
        };
        /** InvitationCreate */
        InvitationCreate: {
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "organization_owner" | "security_admin" | "analyst" | "viewer_auditor" | "maturity_contributor";
        };
        /** InvitationCreatedResponse */
        InvitationCreatedResponse: {
            /** Acceptance Token */
            acceptance_token: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** InvitationResponse */
        InvitationResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** MembershipResponse */
        MembershipResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MembershipUpdate */
        MembershipUpdate: {
            /**
             * Role
             * @enum {string}
             */
            role: "organization_owner" | "security_admin" | "analyst" | "viewer_auditor" | "maturity_contributor";
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * ReadinessResponse
         * @description Readiness: this process can serve a request right now.
         *
         *     Separate from liveness because the two answers have different consequences. Not
         *     ready removes a replica from rotation; not alive restarts it. Confusing them turns
         *     a recoverable dependency outage into a restart loop.
         */
        ReadinessResponse: {
            /** Checks */
            checks?: {
                [key: string]: boolean;
            };
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /** Ready */
            ready: boolean;
        };
        /**
         * RemediationResponse
         * @description What to do about a finding, in both languages.
         *
         *     `review_status` is part of the contract rather than a detail: guidance drafted
         *     from a standard and guidance signed off by a reviewer carry different weight, and
         *     a reader who cannot tell them apart will act on both the same way.
         */
        RemediationResponse: {
            /** Caveat En */
            caveat_en?: string | null;
            /** Caveat Ro */
            caveat_ro?: string | null;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Effort
             * @enum {string}
             */
            effort: "low" | "medium" | "high";
            /** References */
            references?: string[];
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "draft" | "reviewed";
            /** Steps En */
            steps_en?: string[];
            /** Steps Ro */
            steps_ro?: string[];
            /** Summary En */
            summary_en: string;
            /** Summary Ro */
            summary_ro: string;
            /** Template Id */
            template_id: string;
            /** Verification En */
            verification_en: string;
            /** Verification Ro */
            verification_ro: string;
            /** Version */
            version: string;
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "off" | "daily" | "weekly" | "monthly" | "quarterly";
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "passive_observation" | "authorized_assessment";
            /** Next Run At */
            next_run_at?: string | null;
            /** Quiet Hours End */
            quiet_hours_end?: number | null;
            /** Quiet Hours Start */
            quiet_hours_start?: number | null;
            /** Timezone */
            timezone: string;
        };
        /** ScheduleUpdate */
        ScheduleUpdate: {
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "off" | "daily" | "weekly" | "monthly" | "quarterly";
            /**
             * Mode
             * @default passive_observation
             * @enum {string}
             */
            mode: "passive_observation" | "authorized_assessment";
            /** Quiet Hours End */
            quiet_hours_end?: number | null;
            /** Quiet Hours Start */
            quiet_hours_start?: number | null;
            /**
             * Timezone
             * @default Europe/Bucharest
             */
            timezone: string;
        };
        /** ScopeManifestResponse */
        ScopeManifestResponse: {
            /**
             * Algorithm
             * @default EdDSA
             * @constant
             */
            algorithm: "EdDSA";
            /**
             * Authorization Id
             * Format: uuid
             */
            authorization_id: string;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key Id */
            key_id: string;
            /**
             * Manifest Version
             * @default v1
             * @constant
             */
            manifest_version: "v1";
            /** Payload Sha256 */
            payload_sha256: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Authenticated
             * @default true
             * @constant
             */
            authenticated: true;
            /**
             * Contract Version
             * @default v1
             * @constant
             */
            contract_version: "v1";
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activate_global_api_v1_emergency_controls_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_global_api_v1_emergency_controls__control_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                control_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlDeactivate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAccept"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations_api_v1_organizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"][];
                };
            };
        };
    };
    create_organization_api_v1_organizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_api_v1_organizations__organization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_organizations__organization_id__assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_organizations__organization_id__assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_api_v1_organizations__organization_id__assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_organizations__organization_id__assessments__assessment_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_organizations__organization_id__asset_candidates__candidate_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCandidateDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCandidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_v1_organizations__organization_id__audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_authorizations_api_v1_organizations__organization_id__authorizations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_authorization_api_v1_organizations__organization_id__authorizations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentAuthorizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeManifestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_authorization_api_v1_organizations__organization_id__authorizations__authorization_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizationRevoke"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentAuthorizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_domains_api_v1_organizations__organization_id__domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_domain_api_v1_organizations__organization_id__domains_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_api_v1_organizations__organization_id__domains__domain_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_organizations__organization_id__domains__domain_id__asset_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCandidateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainChallengeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainChallengeCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_challenge_api_v1_organizations__organization_id__domains__domain_id__challenges__challenge_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_organizations__organization_id__domains__domain_id__findings_get: {
        parameters: {
            query?: {
                /** @description Resolved findings are excluded by default: the question is normally what is wrong now, and a list mixing fixed with unfixed reads as longer than the problem actually is. */
                include_resolved?: boolean;
            };
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainFindingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_api_v1_organizations__organization_id__domains__domain_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_organizations__organization_id__domains__domain_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_organizations__organization_id__domains__domain_id__schedule_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_controls_api_v1_organizations__organization_id__emergency_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_api_v1_organizations__organization_id__emergency_controls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_v1_organizations__organization_id__emergency_controls__control_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                control_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmergencyControlDeactivate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyControlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invitation_api_v1_organizations__organization_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memberships_api_v1_organizations__organization_id__memberships_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_membership_api_v1_organizations__organization_id__memberships__membership_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_membership_api_v1_organizations__organization_id__memberships__membership_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organization_id: string;
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
}
