"""Render docs/providers/matrix.md from the adapter descriptors.

The document is generated so it cannot drift from the code; CI regenerates it and
fails if the checked-in file differs.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "services" / "worker" / "src"))

from siembiot_worker.adapters.catalog import (  # noqa: E402
    ALL_DESCRIPTORS,
    CORE_CAPABILITIES,
    KEYLESS_DESCRIPTORS,
)
from siembiot_worker.adapters.contract import AdapterDescriptor  # noqa: E402

OUTPUT = ROOT / "docs" / "providers" / "matrix.md"

HEADER = """<!-- Generated by scripts/generate_provider_matrix.py. Do not edit by hand. -->

# Provider matrix

Every collection source declares the same contract: capabilities, terms, data
classification, required secrets, timeout, rate limit, cost unit, cache policy, and
fixture support. An adapter whose secrets are absent stays in the catalog and reports
`unconfigured`; its checks resolve to `unknown`/`unavailable` and never to a pass or a
failure.

The core demo runs on the keyless adapters alone — no paid provider key is required to
collect DNS, e-mail policy, TLS/certificate, HTTP header, RDAP, and Certificate
Transparency evidence.

"""

FOOTER = """
## Reading this table

- **Secrets** — environment variable names only. Values never appear in the repository.
- **Rate limit** — requests per second with burst; a `min-interval` entry additionally
  spaces consecutive calls.
- **Cache** — time-to-live in seconds. A cache is only enabled where provider terms
  permit storage.
- **Classification** — `public_observation` may inform the public projection;
  `tenant_confidential` and `restricted_provider_data` never leave the private workspace.

## Degradation

| Situation | Behaviour |
| --- | --- |
| Adapter secret absent | Adapter reports `unconfigured`; dependent checks are `unknown` |
| Provider rate limit reached | Call refused with `rate_limited`; quota is not consumed |
| Provider quota exhausted | Call refused with `quota_exhausted` and shown on the quota dashboard |
| Repeated provider errors | Circuit opens; calls refused with `circuit_open` until it resets |
| Providers disagree | Every claim is retained and the subject is marked contested |
"""


def _rate_limit(descriptor: AdapterDescriptor) -> str:
    policy = descriptor.rate_limit
    text = f"{policy.max_requests}/{policy.per_seconds:g}s burst {policy.burst}"
    if policy.minimum_interval_seconds:
        text += f", min-interval {policy.minimum_interval_seconds:g}s"
    return text


def _row(descriptor: AdapterDescriptor) -> str:
    secrets = ", ".join(sorted(descriptor.required_secrets)) or "none"
    capabilities = ", ".join(sorted(descriptor.capabilities))
    return (
        f"| `{descriptor.adapter_id}` | {descriptor.version} | {descriptor.group.value} "
        f"| {capabilities} | {descriptor.data_classification.value} | {secrets} "
        f"| {descriptor.timeout_seconds:g}s | {_rate_limit(descriptor)} "
        f"| {descriptor.cost_unit.value} | {descriptor.cache.ttl_seconds}s "
        f"| {'yes' if descriptor.supports_fixtures else 'no'} |"
    )


def render() -> str:
    lines = [HEADER]
    lines.append(
        "| Adapter | Version | Group | Capabilities | Classification | Secrets | Timeout "
        "| Rate limit | Cost | Cache TTL | Fixtures |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    lines.extend(_row(descriptor) for descriptor in ALL_DESCRIPTORS)
    lines.append("")
    lines.append("## Terms and licensing notes")
    lines.append("")
    for descriptor in ALL_DESCRIPTORS:
        lines.append(f"### `{descriptor.adapter_id}` — {descriptor.title}")
        lines.append("")
        lines.append(descriptor.terms_notes)
        if descriptor.terms_url:
            lines.append("")
            lines.append(f"Reference: <{descriptor.terms_url}>")
        if descriptor.licence_notes:
            lines.append("")
            lines.append(f"Licensing: {descriptor.licence_notes}")
        lines.append("")
    lines.append("## Keyless coverage")
    lines.append("")
    lines.append(
        f"{len(KEYLESS_DESCRIPTORS)} of {len(ALL_DESCRIPTORS)} adapters require no secret. "
        f"They cover all {len(CORE_CAPABILITIES)} core capabilities:"
    )
    lines.append("")
    for capability in sorted(CORE_CAPABILITIES):
        lines.append(f"- `{capability}`")
    lines.append(FOOTER)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    document = render()
    if "--check" in sys.argv:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != document:
            print(f"{OUTPUT} is out of date; run scripts/generate_provider_matrix.py")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(document, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
